version: "3"

services:
  app:
    container_name: md5rs-server
    image: simulacraliasing/md5rs-server:latest
    restart: unless-stopped
    ports:
      - "50051:50051"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0'] # specify the GPU device ID to use
              capabilities: [gpu]
    environment:
      TZ: Asia/Shanghai
      MYSQL_URL: "mysql://<user>:<password>@db:3306/<database>"
      REDIS_URL: "redis://cache:6379"
      MD_MODEL: "models/MDV6-yolov9e-1280_d_pp.onnx"
    volumes:
      - <log path>:/app/logs
      - <model path>:/app/models
  
  db:
    container_name: md5rs-mysql
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: <password>
      MYSQL_DATABASE: <database>
      MYSQL_USER: <user>
      MYSQL_PASSWORD: <password>
    volumes:
      - <mysql path>:/var/lib/mysql
    
  cache:
    container_name: md5rs-cache
    image: redis:alpine
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - <redis path>:/data